port 0
tls-port 6391
tls-cert-file /tmp/redis-tls/server.crt
tls-key-file /tmp/redis-tls/server.key
tls-ca-cert-file /tmp/redis-tls/ca.crt
tls-auth-clients no
requirepass examplepassword
appendonly no
save ""
protected-mode no
