port 0
tls-port 26380
tls-cert-file /tmp/redis-tls/server.crt
tls-key-file /tmp/redis-tls/server.key
tls-ca-cert-file /tmp/redis-tls/ca.crt
tls-auth-clients no
sentinel monitor MasterNode 127.0.0.1 6391 1
sentinel auth-pass MasterNode examplepassword
appendonly no
