
name: "SA"

on:
  pull_request:
  push:

jobs:
  static-analysis-psalm:
    name: "Static Analysis with Psalm"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "7.4"

      - name: "Install Relay"
        run: |
          curl -L "https://cachewerk.s3.amazonaws.com/relay/dev/relay-dev-php7.4-debian-x86-64.tar.gz" | tar xz
          cd relay-dev-php7.4-debian-x86-64
          sudo cp relay.ini $(php-config --ini-dir)
          sudo cp relay-pkg.so $(php-config --extension-dir)/relay.so
          sudo sed -i "s/00000000-0000-0000-0000-000000000000/$(cat /proc/sys/kernel/random/uuid)/" $(php-config --extension-dir)/relay.so

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"

      - name: "Run a static analysis with vimeo/psalm"
        run: "vendor/bin/psalm --show-info=false --stats --output-format=github --threads=$(nproc)"
